# Generated by Django 3.2 on 2021-04-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20210425_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
