# Generated by Django 3.2 on 2021-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
